USE [MRP_ROMP]
GO

/****** Object:  StoredProcedure [old].[SP_DIM_UNIVERSITY]    Script Date: 2020-04-09 12:52:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE OR ALTER       PROCEDURE [old].[SP_DIM_UNIVERSITY]
AS
BEGIN

BEGIN TRAN

SET NOCOUNT ON;

DECLARE @TABLE_COUNT INT

DROP TABLE IF EXISTS #OldUniversity

SELECT 
ROW_NUMBER() OVER(ORDER BY UNIVERSITY) AS ROW_ID,
UNIVERSITY INTO #OldUniversity
FROM(
SELECT DISTINCT
SUBSTRING(COLUMN_NAME,CHARINDEX('_',COLUMN_NAME)+1,LEN(COLUMN_NAME)) AS UNIVERSITY
FROM (
SELECT DISTINCT COLUMN_NAME 
FROM generic.table_columns
WHERE 
UPPER(COLUMN_NAME) LIKE 'UNIVERSITY%'
AND UPPER(COLUMN_NAME) NOT LIKE '%OTHER%') AS BASE
) UVI

SELECT @TABLE_COUNT = COUNT(1) FROM old.DimUniversity

IF(@TABLE_COUNT > 0)
BEGIN
DELETE old.DimUniversity
END

INSERT INTO old.DimUniversity
SELECT FORMAT(GETDATE(), 'yyyyMMdd') AS CYCL_TIME_ID,
ROW_ID AS UNIVERSITY_ID,
UNIVERSITY
FROM #OldUniversity
UNION ALL
SELECT 
FORMAT(GETDATE(), 'yyyyMMdd') AS CYCL_TIME_ID,
MAX(ROW_ID) + 1 AS UNIVERSITY_ID,
'Others' AS UNIVERSITY
FROM #OldUniversity

COMMIT TRAN;

END;
GO


