USE [MRP_ROMP]
GO

/****** Object:  StoredProcedure [old].[SP_DIM_QUESTION]    Script Date: 2020-04-09 12:51:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE OR ALTER               PROCEDURE [old].[SP_DIM_QUESTION]
AS
BEGIN

BEGIN TRAN

SET NOCOUNT ON;

DECLARE @TABLE_COUNT INT

SELECT @TABLE_COUNT = COUNT(1) FROM old.DimQuestion

IF(@TABLE_COUNT > 0)
BEGIN
DELETE old.DimQuestion
END

INSERT INTO old.DimQuestion
SELECT 
FORMAT(GETDATE(), 'yyyyMMdd') AS CYCL_TIME_ID,
ROW_NUMBER() OVER(ORDER BY QUESTION) AS QUESTION_ID, 
QUESTION
FROM(
SELECT DISTINCT
CASE WHEN UPPER(QUESTION_HEADING) <> 'NONE' THEN TRIM(REPLACE(REPLACE(SUBSTRING(QUESTION, CHARINDEX('.',QUESTION)+1, LEN(QUESTION)),'?',''),':',''))
ELSE REPLACE(REPLACE(QUESTION,'?',''),':','')
END AS QUESTION
FROM generic.question_answers_list
WHERE TABLE_NAME LIKE 'generic.old_%') BASE

COMMIT TRAN;

END;
GO


