USE [MRP_ROMP]
GO

/****** Object:  StoredProcedure [new].[SP_DIM_COMMUNITY_HOSPITAL]    Script Date: 2020-04-09 12:49:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE OR ALTER               PROCEDURE [new].[SP_DIM_COMMUNITY_HOSPITAL]
AS
BEGIN

BEGIN TRAN

SET NOCOUNT ON;

DECLARE @TABLE_COUNT INT
DECLARE @TABLE_NAME VARCHAR(1000)
DECLARE @COLUMN VARCHAR(4000)
DECLARE @QUERY VARCHAR(MAX) = ''

DROP TABLE IF EXISTS ##ComHosp

SELECT DISTINCT
COLUMN_NUMBER INTO ##ComHosp
FROM generic.table_columns
WHERE UPPER(COLUMN_NAME) LIKE '%FOLLOWING%_COMMUNITY:';

SELECT @COLUMN = COLUMN_NUMBER FROM ##ComHosp;

DROP TABLE IF EXISTS ##CommunityHospital

SET @QUERY = 'SELECT 
ROW_NUMBER() OVER(ORDER BY COMMUNITY) AS COMMUNITY_ID, 
COMMUNITY, 
HOSPITAL INTO ##CommunityHospital
FROM (
SELECT DISTINCT ISNULL(LOCATION,''Others'') AS COMMUNITY, ISNULL((HOSPITAL + '' - '' + LOCATION),''Others'') AS HOSPITAL
FROM (
SELECT DISTINCT
CASE 
WHEN UPPER(COLUMN_NAME) = ''NEW TECUMSEH'' THEN ''New Tecumseth''
WHEN UPPER(COLUMN_NAME) = ''KAWARTHA LAKES'' THEN ''City of Kawartha Lakes''
WHEN UPPER(COLUMN_NAME) IN (''ORILLA'',''ORILIA'') THEN ''Orillia''
WHEN UPPER(COLUMN_NAME) IN (''SOUTHAMPPTON'',''South Hampton'') THEN ''Southampton''
WHEN UPPER(COLUMN_NAME) = ''COBOYRG'' THEN ''Cobourg''
WHEN UPPER(COLUMN_NAME) = ''CLARINGTON'' THEN ''Clarington Township''
WHEN UPPER(COLUMN_NAME) = ''NORTHUMBERLAND COUNTY'' THEN ''Northumberland''
WHEN UPPER(COLUMN_NAME) = ''PORT PERRY HOSPITAL'' THEN ''Port Perry''
WHEN UPPER(COLUMN_NAME) = ''LINDAY'' THEN ''Lindsay''
WHEN UPPER(COLUMN_NAME) = ''PENETANGUISHINE'' THEN ''Penetanguishene''
WHEN UPPER(COLUMN_NAME) = ''OWENSOUND'' THEN ''Owen Sound''
WHEN UPPER(COLUMN_NAME) = ''UXBRIGE'' THEN ''Uxbridge''
WHEN UPPER(COLUMN_NAME) LIKE ''LION%HEAD'' THEN ''Lion''''s Head''
WHEN UPPER(COLUMN_NAME) = ''BARRIE ON'' THEN ''Barrie''
WHEN UPPER(COLUMN_NAME) = ''MARKHAM STOUFFVILLE'' THEN ''Markham''
WHEN UPPER(COLUMN_NAME) = ''CLARKSBURG'' THEN ''Town of Blue Mountains''
WHEN UPPER(COLUMN_NAME) = ''SPRINGWATER'' THEN ''Barrie''
WHEN UPPER(COLUMN_NAME) IN (''FERGUS'',''ELORA'') THEN ''Centre Wellington''
WHEN UPPER(COLUMN_NAME) IN (''STAYNER'',''WASAGA'',''WASAGA BEACH'',''STAYER'') THEN ''Collingwood''
WHEN UPPER(COLUMN_NAME) = ''INNISFUL'' THEN ''Innisfil''
WHEN UPPER(COLUMN_NAME) = ''FLESHERTON'' THEN ''Markdale''
WHEN UPPER(COLUMN_NAME) IN (''OTTAWA'',''ARNPRIOR'') THEN ''North Region''
WHEN UPPER(COLUMN_NAME) IN (''GRAND VALLEY'',''SHELBURNE'') THEN ''Orangeville''
WHEN UPPER(COLUMN_NAME) = ''SAUGEEN SHORES'' THEN ''Port Elgin''
WHEN UPPER(COLUMN_NAME) = ''CAMPBELLFORD'' THEN ''Trent Hills''
WHEN UPPER(COLUMN_NAME) = ''MOUNT FOREST'' THEN ''Wellington North''
ELSE REPLACE(UPPER(dbo.CamelCase(COLUMN_NAME)), '' ONTARIO'','''')
END AS COLUMN_NAME
FROM (
SELECT TRIM(VALUE) AS COLUMN_NAME
FROM (
SELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(COLUMN_NAME,'','',''/''),'' and '',''/''),''&'',''/''),''-'',''/''),''('',''/''),'')'',''/'') AS COLUMN_NAME FROM (
SELECT REPLACE(' + @COLUMN + ',''Barrie, Ontario, Canada'',''Barrie'') AS COLUMN_NAME FROM generic.new_resident_survey
UNION ALL
SELECT REPLACE(' + @COLUMN + ',''Barrie, Ontario, Canada'',''Barrie'') FROM generic.new_student_survey) BASE ) BASE2
CROSS APPLY STRING_SPLIT(BASE2.COLUMN_NAME, ''/'')
) BASE# WHERE UPPER(COLUMN_NAME) NOT IN (''ON'', ''ONTARIO'', '''')
) SB_BASE LEFT JOIN generic.community_hospital_list CHL ON UPPER(SB_BASE.COLUMN_NAME) = UPPER(CHL.COMMUNITY)
) F_BASE'

EXECUTE (@QUERY)

SELECT @TABLE_COUNT = COUNT(1) FROM new.DimCommunity;

IF @TABLE_COUNT > 0
BEGIN

DELETE FROM new.DimCommunity

END

INSERT INTO new.DimCommunity
SELECT 
FORMAT(GETDATE(), 'yyyyMMdd') AS CYCL_TIME_ID,
COMMUNITY_ID,
COMMUNITY,
HOSPITAL
FROM ##CommunityHospital;

COMMIT TRAN;

END;
GO


