USE [MRP_ROMP]
GO

/****** Object:  StoredProcedure [new].[SP_DIM_ROMP_STAFF_RATING]    Script Date: 2020-04-09 12:50:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE OR ALTER         PROCEDURE [new].[SP_DIM_ROMP_STAFF_RATING]
AS
BEGIN

BEGIN TRAN

SET NOCOUNT ON;

DECLARE @TABLE_COUNT INT
DECLARE @DATA_COUNT INT
DECLARE @TABLE_NAME VARCHAR(1000)
DECLARE @QUESTION VARCHAR(4000)
DECLARE @COLUMN VARCHAR(4000)
DECLARE @QUERY VARCHAR(MAX) = ''
DECLARE @UNION_QUERY VARCHAR(MAX) = ''
DECLARE @CNT_DATA INT = 1
DECLARE @CNT_TABLE INT = 1

DROP TABLE IF EXISTS ##RompStaff

SELECT ROW_NUMBER() OVER(PARTITION BY TABLE_NAME ORDER BY COLUMN_NAME) AS ROW_ID,
TABLE_NAME,
COLUMN_NAME,
COLUMN_VALUE INTO ##RompStaff
FROM (
SELECT 
TABLE_NAME,
COLUMN_NAME,
STRING_AGG('IIF('+COLUMN_NUMBER+'<> '''','+COLUMN_NUMBER,',') + ','''')))))' AS COLUMN_VALUE
FROM (
SELECT TABLE_NAME,
TRIM(SUBSTRING(SUBSTRING(COLUMN_NAME,CHARINDEX('_',COLUMN_NAME)+4,LEN(COLUMN_NAME)),0,CHARINDEX(':',SUBSTRING(COLUMN_NAME,CHARINDEX('_',COLUMN_NAME)+4,LEN(COLUMN_NAME))))) AS COLUMN_NAME,
COLUMN_NUMBER
FROM generic.table_columns
WHERE 
UPPER(COLUMN_NAME) LIKE '%ROMP PROGRAM STAFF/RESOURCES%'
AND TABLE_NAME LIKE 'generic.new_%') BASE
GROUP BY TABLE_NAME, COLUMN_NAME
) ROMP

DROP TABLE IF EXISTS ##TableNames

SELECT ROW_NUMBER() OVER(ORDER BY TABLE_NAME) AS ROW_ID, TABLE_NAME INTO ##TableNames FROM(SELECT DISTINCT TABLE_NAME FROM ##RompStaff) TAB;

SELECT @TABLE_COUNT = COUNT(1) FROM ##TableNames;

WHILE @CNT_TABLE <= @TABLE_COUNT
BEGIN

	SELECT @TABLE_NAME = TABLE_NAME FROM ##TableNames WHERE ROW_ID = @CNT_TABLE;

	SELECT @DATA_COUNT = COUNT(1) FROM ##RompStaff WHERE TABLE_NAME = @TABLE_NAME;

	SET @QUERY = ''
	SET @CNT_DATA = 1
	
	WHILE @CNT_DATA <= @DATA_COUNT
	BEGIN

		SELECT @QUESTION = COLUMN_NAME, @COLUMN = COLUMN_VALUE FROM ##RompStaff WHERE ROW_ID = @CNT_DATA AND TABLE_NAME = @TABLE_NAME

		SET @QUERY = @QUERY + @COLUMN + ' AS ''Q' + CAST(@CNT_DATA AS VARCHAR) + ''','

		SET @CNT_DATA = @CNT_DATA + 1
	END

	SET @QUERY = 'SELECT CAST(CAST(COLUMN1 AS FLOAT) AS BIGINT) AS RESPONDENT_ID, ' + SUBSTRING(@QUERY, 0, LEN(@QUERY))
	SET @UNION_QUERY = @UNION_QUERY + @QUERY + ' FROM ' + @TABLE_NAME + ' UNION ALL '

	SET @CNT_TABLE = @CNT_TABLE + 1

END

SET @UNION_QUERY = 'SELECT * INTO ##RompStaffRating FROM ( ' + SUBSTRING(@UNION_QUERY,0,LEN(@UNION_QUERY)-8) + ' ) ROMPSTAFF';

DROP TABLE IF EXISTS ##RompStaffRating

EXECUTE (@UNION_QUERY)

SELECT @TABLE_COUNT = COUNT(1) FROM new.DimROMPRating;

IF @TABLE_COUNT > 0
BEGIN

DELETE FROM new.DimROMPRating

END

INSERT INTO new.DimROMPRating
SELECT 
FORMAT(GETDATE(), 'yyyyMMdd') AS CYCL_TIME_ID,
RESPONDENT_ID,
CASE
	WHEN RATING >= 5 THEN 'Excellent'
	WHEN RATING < 5 AND RATING >= 3.5 THEN 'Good'
	WHEN RATING < 3.5 AND RATING >= 1.5 THEN 'Satisfactory'
	WHEN RATING < 1.5 AND RATING > 0 THEN 'Poor'
	WHEN RATING = 0 THEN 'N/A'
	END AS ROMPStaff_Rating
FROM (
SELECT RESPONDENT_ID,
(Q1_VALUE + Q2_VALUE + Q3_VALUE + Q4_VALUE + Q5_VALUE + Q6_VALUE) AS RATING
FROM (
SELECT
RESPONDENT_ID,
CASE TRIM(UPPER(Q1))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q1_VALUE,
CASE TRIM(UPPER(Q2))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q2_VALUE,
CASE TRIM(UPPER(Q3))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q3_VALUE,
CASE TRIM(UPPER(Q4))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q4_VALUE,
CASE TRIM(UPPER(Q5))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q5_VALUE,
CASE TRIM(UPPER(Q6))
	WHEN 'EXCELLENT' THEN 1
	WHEN 'GOOD' THEN 0.75
	WHEN 'SATISFACTORY' THEN 0.5
	WHEN 'POOR' THEN 0.25
	ELSE 0 END AS Q6_VALUE
FROM ##RompStaffRating ) BASE
) ROMP


COMMIT TRAN;

END;
GO


